name: Unzip Files on Upload

on:
  push:
    branches:
      - main 
    paths:
      - "surveyup.zip"  # This will trigger the action whenever this specific zip file is uploaded

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unzip the file
        run: |
          mkdir unzipped_files
          unzip surveyup.zip -d ./unzipped_files/  # Unzips surveyup.zip to the 'unzipped_files' directory

      - name: Commit unzipped files
        run: |
          git add ./unzipped_files/*
          git commit -m "Unzipped files"
          git push

